/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react'
import { ConfigProvider } from 'antd'
import enUS from 'antd/locale/en_US'
import zhCN from 'antd/locale/zh_CN'
import dayjs from 'dayjs'
import 'dayjs/locale/zh-cn'

export type AppLanguage = 'en' | 'zh'
export type Translate = (text: string, values?: Record<string, string | number>) => string

const zh: Record<string, string> = {
  'English': '英文',
  '中文': '中文',
  'Login': '登录',
  'Email': '电子邮箱',
  'Password': '密码',
  'Remember Me': '记住我',
  'Login Failed': '登录失败',
  'Warehouse Management System': '仓库管理系统',
  'POS System': '销售系统',
  'Sign Out': '退出登录',
  'warehouse_admin': '仓库管理员',
  'pos_admin': '销售管理员',
  'Shipments': '货运',
  'Local Deliveries': '本地送货',
  'Discrepancies': '差异记录',
  'Stock': '库存',
  'Inventory': '库存流水',
  'Generate Reports': '生成报表',
  'Order Slips': '订单',
  'Order slips': '订单',
  'Daily Summary': '每日汇总',
  'Cashiers': '收银员',
  'Save': '保存',
  'Cancel': '取消',
  'Add': '添加',
  'Edit': '编辑',
  'Update': '更新',
  'Delete': '删除',
  'Remove': '移除',
  'Confirm': '确认',
  'Back': '返回',
  'Close': '关闭',
  'Search': '搜索',
  'All': '全部',
  'Yes': '是',
  'No': '否',
  'Active': '启用',
  'Inactive': '停用',
  'Optional': '选填',
  'Required': '必填',
  'Name': '名称',
  'Code': '代码',
  'Type': '类型',
  'Status': '状态',
  'Date': '日期',
  'Address': '地址',
  'Note': '备注',
  'Notes': '备注',
  'Reason': '原因',
  'Product': '产品',
  'Products': '产品',
  'Brand': '品牌',
  'Brands': '品牌',
  'Variety': '品种',
  'Size': '规格',
  'Weight': '重量',
  'Supplier': '供应商',
  'Suppliers': '供应商',
  'Quantity': '数量',
  'Qty': '数量',
  'Sacks': '袋数',
  'Price': '价格',
  'Price / sack': '每袋价格',
  'Unit price': '单价',
  'Subtotal': '小计',
  'Total': '总计',
  'Total amount': '总金额',
  'Value': '价值',
  'Available': '可销售',
  'On hand': '现有库存',
  'Updated': '更新时间',
  'Newest': '最新',
  'Oldest': '最早',
  'Asc': '升序',
  'Desc': '降序',
  'Direction': '方向',
  'In': '入库',
  'Out': '出库',
  'Opening': '期初库存',
  'Unload': '卸货',
  'Order': '订单',
  'Reversal': '冲销',
  'Adjustment': '调整',
  'Local delivery': '本地送货',
  'Local reversal': '本地送货冲销',
  'Documented': '已登记',
  'At port': '已到港',
  'Delivered': '已送达',
  'Unloaded': '已卸货',
  'Cancelled': '已取消',
  'Short': '短缺',
  'Over': '超额',
  'Damaged': '损坏',
  'Undeclared': '未申报',
  'Other': '其他',
  'Paid': '已付款',
  'Partial': '部分付款',
  'Unpaid': '未付款',
  'Payment': '付款状态',
  'Payment status': '付款状态',
  'Payment due': '付款到期日',
  'Due': '到期',
  'Overdue': '已逾期',
  'Article': '商品',
  'Articles': '商品',
  'Cashier': '收银员',
  'Order by': '订购人',
  'Slip': '订单',
  'Slip no.': '订单号',
  'List received': '清单收到日期',
  'Container count': '货柜数量',
  'Container nos.': '货柜编号',
  'Container no.': '货柜编号',
  'Own truck': '自有卡车',
  'International': '国际',
  'Local': '本地',
  'Something went wrong': '发生错误',
  'An unexpected error occurred.': '发生了意外错误。',
  'This action cannot be undone.': '此操作无法撤销。',
  'Delete this record?': '删除此记录？',
  'Discard your changes?': '放弃更改？',
  'Discard logged issues?': '放弃已记录的问题？',
  'Discard': '放弃',
  'Keep editing': '继续编辑',
  'No data': '暂无数据',
  'No articles yet': '尚未添加商品',
  'No reference': '无参考编号',
  'No box': '无货柜编号',
  'Add product': '添加产品',
  'Edit product': '编辑产品',
  'Adjust stock': '调整库存',
  'Save adjustment': '保存调整',
  'Available for sale': '可销售',
  'Selling price / sack': '每袋售价',
  'Notebook code': '记录本代码',
  'Add supplier': '添加供应商',
  'New supplier': '新建供应商',
  'New local supplier': '新建本地供应商',
  'New international supplier': '新建国际供应商',
  'Show inactive cashiers': '显示已停用的收银员',
  'Add cashier': '添加收银员',
  'Add Cashier': '添加收银员',
  'Rename cashier': '重命名收银员',
  'Deactivate': '停用',
  'Reactivate': '重新启用',
  'Cashier added': '已添加收银员',
  'Cashier renamed': '已重命名收银员',
  'Cashier deactivated': '已停用收银员',
  'Cashier reactivated': '已重新启用收银员',
  'Could not load cashiers': '无法加载收银员',
  'No cashiers yet': '尚无收银员',
  'No active cashiers': '没有启用的收银员',
  'Enter a name': '请输入名称',
  'Trash': '回收站',
  'Open Trash': '打开回收站',
  'Back to order slips': '返回订单',
  'Empty Trash': '清空回收站',
  'Empty Trash?': '清空回收站？',
  'Trash is empty': '回收站为空',
  'Could not load Trash': '无法加载回收站',
  'Restore': '恢复',
  'Delete forever': '永久删除',
  'Deleted': '删除时间',
  'Deleted forever': '永久删除时间',
  'Today': '今天',
  'New order slip': '新建订单',
  'Edit order slip': '编辑订单',
  'Delete order slip': '删除订单',
  'Move to Trash': '移至回收站',
  'Order details': '订单详情',
  'Add article': '添加商品',
  'Edit article': '编辑商品',
  'Select cashier': '选择收银员',
  'Search by brand or variant': '按品牌或规格搜索',
  'Search customer, cashier or slip no.': '搜索客户、收银员或订单号',
  'Could not load order slips': '无法加载订单',
  'No order slips in this date range': '此日期范围内没有订单',
  'Order slip not found': '找不到订单',
  "This order slip can't be edited": '此订单无法编辑',
  'View order slip': '查看订单',
  'Order slip moved to Trash': '订单已移至回收站',
  'Products on this page': '本页产品',
  'Sacks on this page': '本页袋数',
  'Net sacks on this page': '本页净袋数',
  'All brands': '所有品牌',
  'All products': '所有产品',
  'All movements': '所有库存变动',
  'Hide zero stock': '隐藏零库存',
  'Available only': '仅显示可销售',
  'Nothing matches these filters': '没有符合筛选条件的记录',
  'Could not load stock': '无法加载库存',
  'Could not load stock logs': '无法加载库存流水',
  'No movements in this date range': '此日期范围内没有库存变动',
  'Stock summary': '库存汇总',
  'Receiving': '收货明细',
  'Report': '报表',
  'Period': '期间',
  'Date range': '日期范围',
  'Source': '来源',
  'Choose filters and press Generate': '选择筛选条件后点击生成',
  'Generate': '生成',
  'Print': '打印',
  'Could not generate report': '无法生成报表',
  'Nothing was received for these filters': '没有符合筛选条件的收货记录',
  'Stock Summary (Inbound)': '入库库存汇总',
  'Receiving Report': '收货报表',
  'Days with arrivals': '有到货的天数',
  'Months with arrivals': '有到货的月份',
  'Sacks received': '收货袋数',
  'Lines': '明细行',
  'Sacks counted': '实点袋数',
  'Variance': '差异',
  'Declared': '申报数量',
  'Counted': '实点数量',
  'Total Sacks': '总袋数',
  'Inbound': '入库',
  'Nothing received in this period': '此期间没有收货记录',
  'Pick a status': '请选择状态',
  'Pick a date': '请选择日期',
  'Pick a reason': '请选择原因',
  'Pick a product': '请选择产品',
  'Pick an article': '请选择商品',
  'Pick a due date': '请选择到期日',
  'Enter a quantity': '请输入数量',
  'Enter a reason': '请输入原因',
  'Search by code or brand': '按代码或品牌搜索',
  'Date unloaded': '卸货日期',
  'Add unlisted item': '添加未列商品',
  'Registered products': '已登记产品',
  'Could not load this container': '无法加载此货柜',
  'Back to shipments': '返回货运',
  'Mark as delivered first': '请先标记为已送达',
  'Any discrepancies?': '是否有差异？',
  'No discrepancies': '无差异',
  'Log discrepancies': '记录差异',
  'Update status': '更新状态',
  'Date arrived at port': '到港日期',
  'Date delivered': '送达日期',
  'Cancellation reason': '取消原因',
  'Previous': '上一页',
  'Next': '下一页',
  'more': '项更多',
  'Discard unsaved changes?': '放弃未保存的更改？',
  'You have unsaved changes that will be lost if you close this window.': '关闭此窗口后，未保存的更改将会丢失。',
  'Keep Editing': '继续编辑',
  '{from}–{to} of {total}': '第 {from}–{to} 项，共 {total} 项',
  'article': '件商品',
  'articles': '件商品',
  'item': '项',
  'items': '项',
  'product': '个产品',
  'products': '个产品',
  'brand': '个品牌',
  'brands': '个品牌',
  'container': '个货柜',
  'containers': '个货柜',
  'sack': '袋',
  'sacks': '袋',
  'qty': '数量',
  'slip': '张订单',
  'slips': '张订单',
  'line': '行',
  'lines': '行',
  'received': '已收货',
  'total': '总计',
  'by': '操作人',
  'rev': '修订',
  'in stock': '库存',
  'out of stock': '缺货',
  'no longer for sale': '已停售',
  'In {count} days': '{count} 天后',
  'Added supplier {name}': '已添加供应商 {name}',
  'Deleted {count} order slips permanently': '已永久删除 {count} 张订单',
  'Restored {slip}': '已恢复 {slip}',
  'Stock adjusted — {count} sacks on hand': '库存已调整——现有 {count} 袋',
  'Only {count} sacks are on hand': '现有库存仅 {count} 袋',
  'Balance becomes {count} sacks': '调整后库存为 {count} 袋',
  'Only {count} in stock': '库存仅 {count}',
  "Can't go above the {count} already on this slip": '不能超过此订单原有的 {count}',
  'No longer for sale: keep up to {count}, the quantity already on this slip': '此商品已停售；最多保留订单原有的 {count}',
  'Every order slip is assigned to a cashier. Cashiers who leave are deactivated, not deleted, so their past slips keep their name.': '每张订单都必须指定收银员。离职收银员会被停用而不是删除，因此历史订单仍会保留其姓名。',
  'Deactivate this cashier?': '停用此收银员？',
  'Reactivate this cashier?': '重新启用此收银员？',
  "They'll no longer be offered for new slips. Existing slips keep them.": '新订单将不能再选择此人，已有订单不受影响。',
  "They'll be offered for new slips again.": '新订单将可以再次选择此人。',
  'One row per order slip. Click a slip number to open it.': '每行显示一张订单。点击订单号可查看详情。',
  "Paid order slips can't be edited": '已付款订单无法编辑',
  'Move this order slip to Trash?': '将此订单移至回收站？',
  'Its sacks go back into stock. You can restore it from Trash within 30 days.': '其商品将退回库存，并可在 30 天内从回收站恢复。',
  "Every slip in Trash is deleted permanently and can't be restored.": '回收站中的所有订单都将被永久删除且无法恢复。',
  'Deleted order slips stay here for 30 days, then are deleted permanently. Their sacks were returned to stock when they were deleted; restoring a slip deducts them again.': '已删除订单会在此保留 30 天，之后永久删除。删除时商品已退回库存；恢复订单时会再次扣减库存。',
  'No deleted slips match your search': '没有符合搜索条件的已删除订单',
  'Restore this order slip?': '恢复此订单？',
  'Its sacks are deducted from stock again.': '其商品数量将再次从库存中扣除。',
  'Delete this order slip permanently?': '永久删除此订单？',
  "It can't be restored afterwards. Stock is not affected.": '删除后无法恢复，库存不会受影响。',
  'Order slip deleted permanently': '订单已永久删除',
  'Order slip created': '订单已创建',
  'Create order slip': '创建订单',
  'Could not create order slip': '无法创建订单',
  'Order slip updated': '订单已更新',
  'Save changes': '保存更改',
  'Could not update order slip': '无法更新订单',
  'No order slip exists with id "{id}".': '不存在编号为“{id}”的订单。',
  'Its sacks are back in stock. You can restore it from Trash within 30 days.': '商品已退回库存。您可在 30 天内从回收站恢复此订单。',
  'Amount paid': '已付金额',
  'Sacks per product': '各产品袋数',
  'Back to today': '返回今天',
  'Reset dates to today': '将日期重置为今天',
  'Could not load the summary': '无法加载汇总',
  'No order slips': '没有订单',
  'Order slips per cashier per day. Click a cashier to see their slips for that day.': '按日期和收银员汇总订单。点击收银员可查看当天订单。',
  'This article is already on the slip': '此商品已在订单中',
  'Assign a cashier': '请选择收银员',
  'No active cashiers — add one on the Cashiers page': '没有启用的收银员——请先在收银员页面添加',
  "Can't be before the slip date": '不能早于订单日期',
  'Customer name (optional)': '客户姓名（选填）',
  'Delivery address (optional)': '送货地址（选填）',
  'Everything entered on this page will be lost.': '此页面输入的所有内容都将丢失。',
  'Stock status': '库存状态',
  'Refresh': '刷新',
  'Product added': '产品已添加',
  'Product updated': '产品已更新',
  'On-hand sacks per product. Quantities are written by the stock ledger, never edited here.': '显示各产品的现有袋数。数量由库存流水记录，不可在此直接修改。',
  'Enter a brand': '请输入品牌',
  'Size (kg)': '规格（公斤）',
  'Enter a sack size': '请输入每袋重量',
  'Fixed after creation': '创建后不可修改',
  'Shorthand like G or P/LAMI': '简称，例如 G 或 P/LAMI',
  'POS hides products with no price. A price on an unavailable product is a leftover.': '销售系统会隐藏未设价格的产品；停售产品显示的价格仅为历史数据。',
  'On hand now': '当前库存',
  'At least 3 characters': '至少输入 3 个字符',
  'Recorded on the movement — the only provenance a manual adjustment has.': '此原因会记录在库存流水中，作为手动调整的依据。',
  'Every movement behind the on-hand figures, newest first. Each row carries the balance it left behind.': '显示构成现有库存的每笔变动，按最新优先排列；每行包含变动后的余额。',
  'Recorded': '记录于',
  'Register Shipment': '登记货运',
  'Packing list': '装箱单',
  'Packing lists with their containers. Only one date applies here, since rows are lists rather than boxes.': '显示装箱单及其货柜。每行代表一张清单，因此仅使用一个日期。',
  'Could not load packing lists': '无法加载装箱单',
  'No packing lists in this date range': '此日期范围内没有装箱单',
  'Select supplier': '选择供应商',
  'Pick a supplier': '请选择供应商',
  'Hauled by our own truck': '由自有卡车运输',
  'No container no.': '无货柜编号',
  'This product is already on this container': '此产品已在该货柜中',
  'Shipment registered': '货运已登记',
  'Discard this shipment?': '放弃此货运记录？',
  'Add New Item': '添加新项目',
  'Add New Container': '添加新货柜',
  'Add container': '添加货柜',
  'Edit container': '编辑货柜',
  'Remove this container?': '移除此货柜？',
  'Its items are removed with it.': '其中的项目也会一并移除。',
  'Submit shipment': '提交货运',
  'Container status:': '货柜状态：',
  'Marked': '已标记为',
  'Pick the port arrival date': '请选择到港日期',
  'Pick the delivery date': '请选择送达日期',
  'Container unloaded — all items matched': '货柜已卸货——所有项目均匹配',
  'Yes, resolve': '有，处理差异',
  'No, all matched': '没有，全部匹配',
  'Log Delivery': '记录送货',
  'Log delivery': '记录送货',
  'Log local delivery': '记录本地送货',
  'All local suppliers': '所有本地供应商',
  'Show voided': '显示已作废记录',
  'Could not load deliveries': '无法加载送货记录',
  'No deliveries in this date range': '此日期范围内没有送货记录',
  'Truck loads from local suppliers, counted as they arrive. There is no packing list to compare against, so stock moves the moment one is logged — a wrong count is corrected by voiding it.': '本地供应商的卡车到货后直接清点。由于没有装箱单可供比对，记录后库存立即增加；数量错误需通过作废记录更正。',
  'Voided': '已作废',
  'Void': '作废',
  'Void delivery': '作废送货记录',
  'Void this delivery?': '作废此送货记录？',
  'Delivery voided — its stock has been reversed': '送货记录已作废——对应库存已冲销',
  'The sacks this delivery added are removed from stock again.': '此送货增加的袋数将从库存中扣除。',
  'Some lines have no price recorded': '部分明细未记录价格',
  'Already on this delivery': '此产品已在本次送货中',
  'What it cost to buy. Optional.': '采购成本（选填）。',
  'Delivery logged — stock updated': '送货已记录——库存已更新',
  'Discard this delivery?': '放弃此次送货记录？',
  'Nothing is saved and no stock moves.': '不会保存任何内容，库存也不会变动。',
  'Select local supplier': '选择本地供应商',
  'Delivery receipt no. (optional)': '送货单编号（选填）',
  'Items counted': '已清点项目',
  'Add Item': '添加项目',
  'No items yet': '尚未添加项目',
  'Open questions': '待确认问题',
  'Mismatches only': '仅显示不匹配',
  'Could not load discrepancies': '无法加载差异记录',
  'No unloaded containers with a variance': '没有存在差异的已卸货货柜',
  'No open questions': '没有待确认问题',
  'Declared vs counted sacks per unloaded container. Negative variance is a shortfall.': '比较每个已卸货货柜的申报袋数与实点袋数；负数差异表示短缺。',
  'Issues logged as Other. They change no quantities and stay here until re-logged under a real reason.': '标记为“其他”的问题不会改变数量，并会保留在此，直到按实际原因重新记录。',
  'Matched': '匹配',
  'resolved': '已解决',
  'Actual sacks counted': '实际清点袋数',
  'Declared on the packing list': '装箱单申报数量',
  'Explain the issue': '请说明问题',
  'Other logs the note only — no quantity changes.': '“其他”仅记录备注，不更改数量。',
  'Edit unlisted item': '编辑未列商品',
  'Log': '记录',
  'issue': '问题',
  'Log issue': '记录问题',
  'Remove this unlisted item?': '移除此未列商品？',
  'Clear this issue?': '清除此问题？',
  'The line goes back to matched.': '此行将恢复为匹配状态。',
  'This container is already unloaded': '此货柜已经卸货',
  'Only delivered containers can be unloaded': '只有已送达的货柜才能卸货',
  'Resolve discrepancies': '处理差异',
  'Lines without an issue are recorded as matching the packing list.': '未记录问题的明细将视为与装箱单一致。',
  'Submit unload': '提交卸货',
  'The container stays delivered and nothing is saved.': '货柜将保持“已送达”状态，且不会保存任何内容。',
  'Timeframe': '时段',
  'Kind': '品类',
  'Export PDF / Print': '导出 PDF / 打印',
  'Start date': '开始日期',
  'Pick a report and filters, then Generate. Export opens the print dialog; choose "Save as PDF" to save a file. Only received stock is counted: pending or cancelled containers and voided deliveries are left out.': '选择报表和筛选条件后点击“生成”。导出会打开打印对话框，可选择“另存为 PDF”。报表只统计已收货库存，不包括待处理或已取消的货柜及已作废的送货记录。',
  'Inbound sacks per brand, by the day they arrived: containers on their unload date (counted sacks) and local deliveries on the date received.': '按品牌和到货日期汇总入库袋数：货柜按卸货日期统计实点袋数，本地送货按收货日期统计。',
  'Every line received in the date range, grouped by supplier, with declared vs counted sacks and value.': '按供应商分组显示日期范围内的每条收货明细，包括申报、实点袋数和价值。',
  'Movement': '库存变动',
  'Change': '变动数量',
  'Balance after': '变动后余额',
  'Received': '收货日期',
  'Reference': '参考编号',
  'Issues': '问题',
  'Actual': '实际数量',
  'Container': '货柜',
  'Items match': '项目匹配',
  'Logged': '记录时间',
  'Amount': '金额',
  'Weekly': '每周',
  'Bi-weekly': '每两周',
  'Monthly': '每月',
  'Yearly': '每年',
  'Custom': '自定义',
  'shipments only': '仅货运',
  'local deliveries only': '仅本地送货',
  'Shipment': '货运',
  'International (containers)': '国际（货柜）',
  'Local (truck deliveries)': '本地（卡车送货）',
  'Optional, e.g. Japonica': '选填，例如 Japonica',
  'e.g. Opening count, warehouse audit': '例如期初盘点、仓库审计',
  'e.g. Counted twice by mistake': '例如误重复清点',
  'e.g. OCLU1395985 — leave blank if none': '例如 OCLU1395985；没有则留空',
}

const interpolate = (text: string, values?: Record<string, string | number>) =>
  values
    ? Object.entries(values).reduce(
        (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
        text,
      )
    : text

interface LanguageContextValue {
  language: AppLanguage
  setLanguage: (language: AppLanguage) => void
  toggleLanguage: () => void
  t: Translate
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<AppLanguage>(() =>
    localStorage.getItem('appLanguage') === 'zh' ? 'zh' : 'en',
  )

  useEffect(() => {
    localStorage.setItem('appLanguage', language)
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
    dayjs.locale(language === 'zh' ? 'zh-cn' : 'en')
  }, [language])

  const value = useMemo<LanguageContextValue>(() => {
    const t: Translate = (text, values) =>
      interpolate(language === 'zh' ? (zh[text] ?? text) : text, values)
    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'zh' : 'en')),
      t,
    }
  }, [language])

  return (
    <LanguageContext.Provider value={value}>
      <ConfigProvider locale={language === 'zh' ? zhCN : enUS}>
        {children}
      </ConfigProvider>
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider')
  return context
}

export function LanguageToggle({ compact = false }: { compact?: boolean }) {
  const { language, setLanguage } = useLanguage()
  return (
    <div className="language-toggle" role="group" aria-label="Language">
      <button
        type="button"
        className={language === 'en' ? 'active' : ''}
        onClick={() => setLanguage('en')}
        aria-pressed={language === 'en'}
      >
        {compact ? 'EN' : 'English'}
      </button>
      <span aria-hidden="true">/</span>
      <button
        type="button"
        className={language === 'zh' ? 'active' : ''}
        onClick={() => setLanguage('zh')}
        aria-pressed={language === 'zh'}
      >
        中文
      </button>
    </div>
  )
}
